
version: '3.8'

services:
  postgres_db:
    image: postgres:16
    environment:
      POSTGRES_USER: arciniegas_cristian
      POSTGRES_PASSWORD: 1014736782
      POSTGRES_DB: arciniegas_cristian_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

